server:
  port: 5000
spring:
  application:
    name: Url_Shortener
    id_gen_service: http://localhost:80

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
  data:
    redis:
      host: 127.0.0.1
      port: 9000
  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
